service: shop-aws-node-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: default
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

functions:
  getProductsList:
    handler: src/functions/index.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductById:
    handler: src/functions/index.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
