service: shop-aws-node-authorization-service
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION}
  profile: default

  httpApi:
    cors: true
  logs:
    httpApi: true

functions:
  basicAuthorizer:
    handler: src/functions/index.basicAuthorizer

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: "node18"
