service: shop-aws-node-import-service
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:region}
  profile: default
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - ${env:BUCKET}

functions:
  importProductsFile:
    handler: functions/index.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
