service: shop-aws-node-import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: default
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:

resources:
  Resources:

functions:

plugins:
  - serverless-esbuild
  - serverless-offline
